# これは Release Please App の設定です
# 注: `.yml` しか受け付けないため、拡張子を変更しないでください

primaryBranch: main
handleGHRelease: true
manifest: true
manifestConfig: release-please-config.json
manifestFile: .release-please-manifest.json
