name: Deploy (Staging)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-staging:
    name: Deploy (Staging)
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - name: deploy
        uses: appleboy/ssh-action@v1
        env:
          DEPLOY_TARGET_DIR: ${{ secrets.DEPLOY_TARGET_DIR }}
          DEPLOY_BUILD_OUTPUT_DIR: ${{ secrets.DEPLOY_BUILD_OUTPUT_DIR }}
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_SECRET_KEY }}
          envs: DEPLOY_TARGET_DIR,DEPLOY_BUILD_OUTPUT_DIR
          script: |
            set -euxo pipefail

            cd kaniwriter
            git checkout main
            git pull
            pnpm install --frozen-lockfile
            pnpm build:ceres

            find "${DEPLOY_TARGET_DIR}" -type f -print0 | xargs -0 rm -rf
            cp -r "${DEPLOY_BUILD_OUTPUT_DIR}/*" "${DEPLOY_TARGET_DIR}"
